### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by baldurh**
This adds an EditorHandler which is created for every active TextEditor.
Also refactors some of the git code to use Atom’s internal git support.
This is heavily inspired by the `git-diff` atom package.

### TODO
- [] Better handling of projects without git repositories

### CODE REVIEW

**Comment by baldurh** [comment]
@MoritzKn, @granteagon You have shown some interest in this package. I’m going to test this new version for a few days and thought maybe you would be interested in trying this out as well 😄

**Comment by granteagon** [comment]
@baldurh thanks man, I'll check it out

**Comment by MoritzKn** [comment]
Yeah thanks! I will test it a bit

**Comment by baldurh** [comment]
I added a few commits just now. I removed a bit of code which was attempting to keep track of added and modified lines before the file was saved. It was too much of a headache. At least for now. So instead I added a ‘Unsaved’ message so that the user wouldn’t see wrong blame information. Please let me know what you think 🙂

**Comment by baldurh** [comment]
I have yet to experience any major issues with this version. I will probably release this by the end of the week.

**Comment by granteagon** [comment]
Working well for me also

**Pull request merged**
